#######################################################
# 
# DataPreprocessor.py
# Python implementation of the Class DataPreprocessor
# Generated by Enterprise Architect
# Created on:      12-Nov-2024 12:04:03 AM
# Original author: utilizator
# 
#######################################################


class DataPreprocessor:
    def preprocess_post(self, post_content: str):
        return post_content