#######################################################
# 
# MongoDbClient.py
# Python implementation of the Class MongoDbClient
# Generated by Enterprise Architect
# Created on:      12-Nov-2024 12:04:03 AM
# Original author: utilizator
# 
#######################################################

from django.conf import settings
from pymongo import MongoClient


class MongoDbClient:
    _client = None

    def get_db(self):
        if self._client is None:
            self._client = MongoClient(settings.MONGODB_SETTINGS['URI'])
        return self._client[settings.MONGODB_SETTINGS['DB_NAME']]
