#######################################################
# 
# RedditPostsRepository.py
# Python implementation of the Class RedditPostsRepository
# Generated by Enterprise Architect
# Created on:      12-Nov-2024 12:04:03 AM
# Original author: utilizator
# 
#######################################################
from api.data.MongoDbClient import MongoDbClient
from api.data.RedditPost import RedditPost


class RedditPostsRepository:
    def __init__(self):
        self.db = MongoDbClient().get_db()
        self.collection = self.db['reddit_posts']

    def get_all(self):
        posts = self.collection.find()
        return [RedditPost.from_dict(post) for post in posts]

    def save(self, post: RedditPost):
        self.collection.update_one({"_id": post.id}, {"$set": post.__dict__()}, upsert=True)
